# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 15:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0002_auto_20161025_0758'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 10, 27, 15, 59, 31, 877825, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='album',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 10, 27, 15, 59, 45, 667199, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photo',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='photodislike',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='photolike',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='description',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
